#! /bin/sh
# autostart
exec $HOME/scripts/bash/autostart.sh &
exec $HOME/scripts/bash/wpp -c $HOME/Pictures/Wallpapers/saturn_4k.jpg &
exec sudo powertop --auto-tune &
exec emacs --daemon &> /dev/null &
ffplay -nodisp -autoexit -volume 15 $HOME/.resources/boot_sound.mp3 >/dev/null 2>&1 &

killall picom 
picom --experimental-backends &

# setup workspaces
bspc monitor eDP1 -d I II III IV V

killall mpd
mpd &

# get xrdb colors
highlight=$(xrdb -query | grep "*.highlight" | cut -f 2)
background=$(xrdb -query | grep "*.background" | cut -f 2)

# config bindings
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_corner 
# config window properties
bspc config border_width 0
bspc config window_gap 0
bspc config top_padding 35
bspc config border_radius 0
# more configs
bspc config focus_follows_pointer true
bspc config focused_border_color "$highlight"
bspc config normal_border_color "$background"
bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle false

# rules
bspc rule -a "Emacs" state=fullscreen
bspc rule -a "*:*:emacs-run-launcher" state=floating
bspc rule -a "pinentry-qt" state=floating
