#! /bin/sh

exec $HOME/scripts/bash/autostart.sh &
exec feh --bg-fill ~/Pictures/Wallpapers/wpp.png &>/dev/null &
#exec $HOME/scripts/bash/quotewpp.sh &
exec urxvt -e sh -c "bspc node -t floating && bspc node -z top 200 200 && bspc node -v 0 -475 &&$HOME/scripts/bash/palette.sh && zsh" &
ffplay -nodisp -autoexit -volume 15 $HOME/.resources/boot_sound.mp3 >/dev/null 2>&1 &

killall compton
compton --dbus &

bspc monitor eDP-1 -d DEV WWW DOC ETC MEDIA 

killall mpd
mpd &

bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_corner 

bspc config border_width 5
bspc config window_gap 30
bspc config top_padding 60
bspc config left_padding 30
bspc config right_padding 30
bspc config border_radius 15

#get xrdb colors
highlight=$(xrdb -query | grep "*.highlight" | cut -f 2)
background=$(xrdb -query | grep "*.background-no-transparancy:" | cut -f 2)

bspc config focused_border_color "$highlight"
bspc config normal_border_color "$background"

bspc config focus_follows_pointer true
bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle false

